// Writes the website's copy of Neptune's bundled palettes from the app's
// generated catalog. Run from `website/` after `scripts/import-themes.py`
// changes it: `bun scripts/generate-themes.mjs`.

const source = await Bun.file("../src/theme_catalog.rs").text();
const themes = [...source.matchAll(/name: "((?:[^"\\]|\\.)*)", colors: ThemeColors::from_rgb\(\[([^\]]+)\]\)/g)].map(
  ([, name, values]) => {
    const colors = values.split(",").map((value) => value.trim().replace(/^0x/, ""));
    if (colors.length !== 23 || colors.some((color) => !/^[0-9a-f]{6}$/.test(color))) {
      throw new Error(`Unexpected colors for ${name}`);
    }
    return [JSON.parse(`"${name}"`), colors.join("")];
  },
);
if (themes.length === 0) throw new Error("No themes found");

await Bun.write(
  "src/components/neptune/theme-catalog.ts",
  `// Generated by scripts/generate-themes.mjs from src/theme_catalog.rs. Do not edit.
// License and credits for the palettes: assets/themes/.
// Each theme is its name and 23 colours as RRGGBB: background, foreground,
// bold, cursor, cursor text, selection, selected text, then the 16 ANSI colours.
export const BUNDLED: readonly (readonly [string, string])[] = ${JSON.stringify(themes)};
`,
);
console.log(`${themes.length} themes`);
