#!/usr/bin/env python3
"""Regenerate the offline theme catalog from a pinned iTerm2-Color-Schemes checkout.

Usage: python3 scripts/import-themes.py /path/to/iTerm2-Color-Schemes
No network access or execution of upstream code. See assets/themes/README.md.
"""
import hashlib
import json
from pathlib import Path
import plistlib
import shutil
import subprocess
import sys

REPO = Path(__file__).resolve().parents[1]
REVISION = '450b05ea0962456b424e5736aed0bec7fd147f28'


def rgb(value):
    channels = [value[f'{c} Component'] for c in ('Red', 'Green', 'Blue')]
    if not all(isinstance(c, (int, float)) and 0 <= c <= 1 for c in channels):
        raise ValueError('Invalid RGB channels')
    # Match upstream tools/gen.py: Display P3 is converted to sRGB; legacy
    # Calibrated/unspecified values use their stored RGB components.
    if value.get('Color Space', '').strip() == 'P3':
        linear = [c / 12.92 if c < .04045 else ((c + .055) / 1.055) ** 2.4 for c in channels]
        matrix = ((1.22494018, -.22469880, -.00012973),
                  (-.04205631, 1.04203282, -.00000601),
                  (-.01963755, -.07862814, 1.09826365))
        channels = []
        for row in matrix:
            c = max(0, min(1, sum(a*b for a, b in zip(row, linear))))
            channels.append(12.92*c if c < .0031308 else 1.055*c**(1/2.4)-.055)
    return sum(round(c*255) << shift for c, shift in zip(channels, (16, 8, 0)))


def main():
    source = Path(sys.argv[1])
    revision = subprocess.check_output(['git', '-C', str(source), 'rev-parse', 'HEAD'], text=True).strip()
    if revision != REVISION:
        raise ValueError(f'Expected upstream revision {REVISION}, got {revision}')
    dirty = subprocess.check_output(['git', '-C', str(source), 'status', '--porcelain', '--untracked-files=all', '--', 'schemes', 'LICENSE', 'CREDITS.md'], text=True)
    if dirty:
        raise ValueError('Upstream scheme/license inputs must be unmodified')
    output = REPO / 'assets/themes'
    output.mkdir(parents=True, exist_ok=True)
    entries = []
    hashes = {}
    for path in sorted((source/'schemes').glob('*.itermcolors')):
        raw = path.read_bytes()
        hashes[path.name] = hashlib.sha256(raw).hexdigest()
        data = plistlib.loads(raw)
        variants = [''] + [f' ({v})' for v in ('Dark', 'Light') if f'Background Color ({v})' in data]
        for variant in variants:
            def get(key, fallback=None):
                value = data.get(key+variant, data.get(key))
                return rgb(value) if value is not None else fallback
            colors = [get('Background Color'), get('Foreground Color'),
                      get('Bold Color', get('Foreground Color')), get('Cursor Color'),
                      get('Cursor Text Color', get('Background Color')), get('Selection Color'),
                      get('Selected Text Color', get('Foreground Color'))]
            colors += [get(f'Ansi {i} Color') for i in range(16)]
            name = path.stem + variant
            entries.append((name, colors))
    entries.sort(key=lambda e: e[0])
    assert len({name for name, _ in entries}) == len(entries), 'Duplicate theme IDs'
    lines = ['// Generated by scripts/import-themes.py. Do not edit.',
             f'// Upstream {REVISION}; license and credits: assets/themes/.',
             'use super::{BundledTheme, ThemeColors};', '#[rustfmt::skip]',
             'pub static BUNDLED: &[BundledTheme] = &[']
    for name, colors in entries:
        values = ', '.join(f'0x{c:06x}' for c in colors)
        lines.append(f'    BundledTheme {{ name: {json.dumps(name, ensure_ascii=False)}, colors: ThemeColors::from_rgb([{values}]) }},')
    lines.append('];\n')
    (REPO/'src/theme_catalog.rs').write_text('\n'.join(lines))
    for name in ('LICENSE', 'CREDITS.md'):
        shutil.copyfile(source/name, output/name)
    (output/'source.json').write_text(json.dumps({'repository': 'https://github.com/mbadolato/iTerm2-Color-Schemes', 'revision': revision, 'schemes': hashes, 'presets': len(entries)}, indent=2)+'\n')
    print(f'Imported {len(hashes)} schemes, {len(entries)} presets including embedded variants')


if __name__ == '__main__':
    main()
